### ISSUE TITLE
structured the models properly

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#1]

**Comment by theanshulcode** [comment]
Could you please explain exactly what is the issue? @Niketkumardheeryan

**Comment by Niketkumardheeryan** [comment]
@theanshulcode we just have to arrange the model on the basis of difficulty of a model(in Readme. Md file)

**Comment by NikhiIsaac** [comment]
can you assign me this issue

**Comment by NikhiIsaac** [comment]
after arranging the models in sequence I have to list it out in the readme file . right?

**Comment by Niketkumardheeryan** [comment]
@NikhiIsaac yep,
