### ISSUE TITLE
Adding LGMSOC logo 

### ISSUE THREAD

**Issue by payaldutta** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#100]
Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section I will like to work on this issue under LGMSOC @Niketkumardheeryan

**Comment by Niketkumardheeryan** [comment]
@payaldutta i removed it yesterday, if u want to really work  only for simple then you can more improve the Readme.md file. otherwise there is no logos and required
