### ISSUE TITLE
Ola Bike Ride Request Demand Forecast

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#104]

**Comment by Soumayan-pal01** [comment]
Hey @Niketkumardheeryan I would like on this issue. Please assign me if possible. Thank you.

**Comment by Soumayan-pal01** [comment]
Thank you @Niketkumardheeryan . I will be working on the 'Model Creation' part to perform a comparative analysis using different models after doing data preprocessing and visualizations. I will inform once I have created the PR.

**Comment by Soumayan-pal01** [comment]
I have created the PR. Please review it @Niketkumardheeryan . Thank you.
