### ISSUE TITLE
Speech Emotion Recognition

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#105]

**Comment by psyduck1203** [comment]
Hey, Can I work on this issue?

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by psyduck1203** [comment]
Hey, @harshita9621 I'm already working on this issue. Can you please choose some other issue to work on!

**Comment by Megha0606** [comment]
Hey it's more than 10 days, someone else should get an opportunity to work also? 
I hope you consider this
