### ISSUE TITLE
Improve Readme.md file ...

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#120]

**Comment by Akash20x** [comment]
@Niketkumardheeryan Please assign me this issue as a part of LGM-SOC'21 and give some description what I have to improve it in README.md

**Comment by Niketkumardheeryan** [comment]
@Akash20x add the content of the repository into readme.md file and some unique or latest feature.

**Comment by Akash20x** [comment]
@Niketkumardheeryan OK I will do it, please assign me this issue.

Basically, I will add all projects names and short description in the last and I will also improve Get Started, have a look, Contributing guidelines section and also add some more topics and it's description in the topic section.

**Comment by Niketkumardheeryan** [comment]
@Akash20x automate the project section

**Comment by Akash20x** [comment]
> @Akash20x automate the project section

OK

**Comment by Akash20x** [comment]
@Niketkumardheeryan Please check my pull request

**Comment by Akash20x** [comment]
@Niketkumardheeryan
Please close this issue
