### ISSUE TITLE
Face_Detection using Open Cv

### ISSUE THREAD

**Issue by anubhav201241** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#127]
I want to contribute to your project by adding Face and Eye detection part with the help of Opencv and Python
In which it can detect the face, eye, and middle part of the face with the use of open cv and Python

@Niketkumardheeryan Kindly assign this issue to me under the label of LGMSOC'21

**Comment by Niketkumardheeryan** [comment]
@anubhav201241 someone is working on this issue...
