### ISSUE TITLE
Create a Deep learning Model for object detection..

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#13]

**Comment by NikhiIsaac** [comment]
ill like to make the model using darkflow and yolo v5
if there is something more specific you need pls tell
could you assign me this issue

**Comment by PadminiRai** [comment]
I'd like to work on this issue under label LGMSOC21.

**Comment by Niketkumardheeryan** [comment]
@PadminiRai go for it.

**Comment by Abhilash249** [comment]
I would also like to contribute under LGMSOC21

**Comment by PadminiRai** [comment]
@Niketkumardheeryan I've created the PR for this issue. 
**PR** : https://github.com/Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-/pull/114
