### ISSUE TITLE
Exports classification of Canada

### ISSUE THREAD

**Issue by abhisheks008** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#136]
Hey @Niketkumardheeryan, I am up for this issue and I want to contribute in this.

Name of the issue : Exports classification of Canada

- [x] LGMSOC Participant

Approach : For this classification model I would like to use Random forest, decision tree, linear regression and some more algorithms. After that I'll evaluate them based on the accuracy scores.

Description : This project is all about deploying the classification model.

Task Taken : Developing the classification model for this project.

Please assign me this issue.

**Comment by Niketkumardheeryan** [comment]
@abhisheks008 no more simple classification required...
