### ISSUE TITLE
Stock Price Changes Prediction

### ISSUE THREAD

**Issue by akash435** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#143]
In this I will develop a model which will predict the prices of stock whether it will increase or decrease using stock news.

Will be using various libraries like numpy, scikit learn, matplotlib

And in algorithm will use random forrest.

And predict whether the stock price will increase or decrease.

**Comment by akash435** [comment]
@Niketkumardheeryan ,please assign this to me under LGM SOC.

**Comment by Niketkumardheeryan** [comment]
@akash435 check issue no . #37
