### ISSUE TITLE
Heart disease prediction.

### ISSUE THREAD

**Issue by ASLManasa** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#147]
I am LGM SoC21 participant. I want to create heart predection model by improving the accuracy and comparing different models. Kindly assign me this issue.Thanks

**Comment by suy1968** [comment]
Please assign me as I am a participant of LGMSOC'21.

**Comment by ASLManasa** [comment]
@Niketkumardheeryan Sir, I have made a pr Kindly look into it. Thank you.
