### ISSUE TITLE
fraud credit card detection

### ISSUE THREAD

**Issue by ASLManasa** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#148]
I am LGM SoC21 participant. I want to create a model for fraud  credit card detection using Machine Learning. Kindly assign me this issue.Thanks

**Comment by suy1968** [comment]
Please Assign me this issue as I am a participant of LGMSOC'21.

**Comment by ASLManasa** [comment]
@Niketkumardheeryan can I start working on this.

**Comment by Niketkumardheeryan** [comment]
yup...
@ASLManasa But the accuracy of the model must be high without under or overfitting..

**Comment by ASLManasa** [comment]
@Niketkumardheeryan ok I will try to do so. Thanks.
