### ISSUE TITLE
A Chat-bot for medical help

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#15]

**Comment by Akash20x** [comment]
@Niketkumardheeryan I want to take up this issue as a part of LGM-SOC'21.

Kindly assign me this issue and specify some description about the issue

**Comment by Niketkumardheeryan** [comment]
@Akash20x  create a chatbot that could provide medical assistance for patients of the hospital,
some functions those you can add-

*  bed available 
*  Useful contact details 
* about the hospital.
add more things accordingly...

you can take references from others chatbot as well.

**Comment by Akash20x** [comment]
@Niketkumardheeryan Please also add lgm-soc'21 label

**Comment by Niketkumardheeryan** [comment]
@Akash20x  don't worry , i will

**Comment by Akash20x** [comment]
@Niketkumardheeryan Please assign this to anyone else as I have a lot of work from my internship and college so I can't focus on open source projects for a week.

**Comment by usgn94** [comment]
@Niketkumardheeryan I would like to work on this issue. Could you please assign me

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan I want to work on this issue. So please assign this issue to me.
