### ISSUE TITLE
Random forest test

### ISSUE THREAD

**Issue by manognyaa** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#168]
Hello sir,
I would like to work on this issue, please assign this to me @Niketkumardheeryan sir.

**Comment by Niketkumardheeryan** [comment]
@manognyaa what is random forest Test

**Comment by manognyaa** [comment]
@Niketkumardheeryan sir, actually it is a process of combining multiple classifiers to solve a complex problem and to improve the performance of the model.

steps it will follow :
i. Starts by selecting random samples from given dataset using the bootstrap technique.
ii. This algorithm will construct a decision tree for every sample, then it will get prediction result from each decision tree.
iii. Next, voting will be performed for every predicted result.
iv. At last, select the most voted prediction as the final prediction result.
