### ISSUE TITLE
Create a Time series forecasting  Model .

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#18]

**Comment by psyduck1203** [comment]
Hey I'm a participant of LGM-SoC and I want to work on this issue. Can you please assign me this issue!

**Comment by Niketkumardheeryan** [comment]
@psyduck1203 first complete another issue..

**Comment by ayushi424** [comment]
Hey @Niketkumardheeryan,
I would like to work on this issue.
I'll proceed by using Facebook prophet model for forecasting.
Please assign.
