### ISSUE TITLE
Create a file ,which contain the code for different types of  Hypothesis testing.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#19]

**Comment by vaibhavgupta2499** [comment]
Can I work on this issue as LGM-SOC participant ?

**Comment by Niketkumardheeryan** [comment]
sure @vaibhavgupta2499

**Comment by vaibhavgupta2499** [comment]
I have added a Pull request for this issue, kindly please check that and revert back. Please consider this for LGM-SOC participation.
