### ISSUE TITLE
Xgboost from scratch 

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#2]

**Comment by Rutikab12** [comment]
Hey, @Niketkumardheeryan I would like to work on this issue as letsgrowmore SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Niketkumardheeryan** [comment]
sure @Rutikab12

**Comment by Rutikab12** [comment]
Thank You.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!
