### ISSUE TITLE
Car Price Prediction Using Simple Linear Regression

### ISSUE THREAD

**Issue by Sakalya100** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#21]
I will make a Machine Learning Model using Simple Linear regression for Predicting the Car Price .

**Comment by Sakalya100** [comment]
Please assign me this issue. I will start working on it.

**Comment by Niketkumardheeryan** [comment]
@Sakalya100 sorry ,i don't want more simple regression model, make other issue or choose one.

**Comment by Sakalya100** [comment]
Can I make an issue on multiple regression model?
