### ISSUE TITLE
Flight Delay prediction

### ISSUE THREAD

**Issue by Komal-99** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#22]
Can i Add jupyter notebook for the flight delay prediction for the dataset available on kaggel . with proper comments about the python library used. 
I am LGMSOC participant 
https://www.kaggle.com/usdot/flight-delays

**Comment by Niketkumardheeryan** [comment]
@Komal-99 your model must be optimized ..

**Comment by Komal-99** [comment]
okay sure but can you please tell me location or folder where to create folder for uploading dataset and  file?

**Comment by Niketkumardheeryan** [comment]
@Komal-99 create a folderect named as ur proj and add dataset files into it ,than make a pr

**Comment by Komal-99** [comment]
okay
