### ISSUE TITLE
Build Google Search Algorithm with Python.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#24]

**Comment by queenish001** [comment]
Sir, Kindly assign this issue to me.

**Comment by Umesh-01** [comment]
@Niketkumardheeryan sir may I work on this??

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan can you please assign this issue to me? I saw its up for grab. I will use beautifulsoup4 ,request and response library
