### ISSUE TITLE
Deploy a Chatbot with Python into a Web Application

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#26]

**Comment by Jyoti6828** [comment]
Can you please assign this issue to me. I want to create Covid-19 related Chatbot using Python and real-time API.

**Comment by Niketkumardheeryan** [comment]
sure @Jyoti6828

**Comment by rammya29** [comment]
Since it is posted as up for grab can I work on this issue?

**Comment by Niketkumardheeryan** [comment]
@rammya29 sure
