### ISSUE TITLE
Predict Weather with Machine Learning

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#28]

**Comment by PadminiRai** [comment]
I'd like to work on this issue under LGMSOC'21.

**Comment by suy1968** [comment]
Please assign me as I am participant of LGMSOC-21

**Comment by PadminiRai** [comment]
I'm working on this issue right now .

**Comment by Megha0606** [comment]
Please assign me this issue

**Comment by PadminiRai** [comment]
I'm at the verge of completion of this issue.

**Comment by Niketkumardheeryan** [comment]
@PadminiRai ok, but do it fast.

**Comment by PadminiRai** [comment]
@Niketkumardheeryan I'm just working on identify the pointers through which I can increase accuracy and precision of my model.

**Comment by PadminiRai** [comment]
@Niketkumardheeryan I've created the PR for this issue .
**PR** : https://github.com/Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-/pull/112
