### ISSUE TITLE
Amazon Products Reviews Sentiment

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#29]

**Comment by queenish001** [comment]
As an LGMSoC participant, I'd like to work on this issue.
Kindly assign it to me :)

**Comment by Ak12hil** [comment]
I'm LMSOC participant...can I work on this?

**Comment by SwatiPanchal** [comment]
I know ML well so I would request you to please assign this project to me

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan  can you please assign this issue to me? I saw its up for grab

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan can you please assign this issue to me? I saw its up for grab
