### ISSUE TITLE
Explaination and Example for P value with code

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#3]
Show the importance of P value..

**Comment by Sumit11081996** [comment]
Hii, @Niketkumardheeryan I would like to work on this issue as LCM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hey, @Niketkumardheeryan I would like to work on this issue as LSM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Niketkumardheeryan** [comment]
@Sumit11081996 go for it.

**Comment by Niketkumardheeryan** [comment]
> Hey, @Niketkumardheeryan I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank

**Comment by Sumit11081996** [comment]
thank you @Niketkumardheeryan  i will do my best
