### ISSUE TITLE
Implementing various Classification algorithms

### ISSUE THREAD

**Issue by Sakalya100** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#31]
I will implement various classification algorithms on a dataset.

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Please assign me this issue. I would like to work on this.

**Comment by Niketkumardheeryan** [comment]
@Sakalya100 are you working on other issues...

**Comment by Sakalya100** [comment]
@Niketkumardheeryan No sir I am not working on any other issues.
