### ISSUE TITLE
Tesla Stock Market Prediction with Sentiment Analysis

### ISSUE THREAD

**Issue by Thatsooraj** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#37]
I would like to contribute through the project based on neural networks with NlP .. LSTM (RNN + NLP) on Tesla stock market prediction

**Comment by Niketkumardheeryan** [comment]
@Thatsooraj go for it .

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan can you please assign this issue to me? I saw its up for grab
