### ISSUE TITLE
Data Analysis and Machine Learning Projects

### ISSUE THREAD

**Issue by theanshulcode** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#4]
Can I include projects related to Data Analysis and ML in this?

**Comment by Niketkumardheeryan** [comment]
sure @theanshulcode ,But it should be a standard Project, which can help to get a job or internship in Data science field. Ex. Reccomendation system or many more ..

**Comment by theanshulcode** [comment]
I want to work on Customer Segmentation Analysis using Machine Learning. In this project, I will be using Unsupervised ML Algorithm called Clustering.

Can I work on it @Niketkumardheeryan ?

**Comment by Niketkumardheeryan** [comment]
@theanshulcode go for it,but it will be great if you will code a cluster method from scratch for your dataset.

**Comment by theanshulcode** [comment]
Thank you @Niketkumardheeryan

**Comment by Sumit11081996** [comment]
Hi, @Niketkumardheeryan I would like to work on this issue as LCM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hii, @Niketkumardheeryan I would like to work on this issue as LSM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by ayushi424** [comment]
Hello, I would like to contribute a data analytics project Predictive Analytics using python.
 May I work on it @Niketkumardheeryan ??

**Comment by Niketkumardheeryan** [comment]
@harshita9621 @ayushi424 @Sumit11081996 ,you can choose another issue, bcz someone is working on it..

**Comment by theanshulcode** [comment]
Hi @Niketkumardheeryan

I wan to work on Data Analysis on Covid-19. Please assign me this task.

**Comment by UditKaushish** [comment]
Hi @Niketkumardheeryan  I want to work on breast cancer prediction model in which I will use various ml algorithm and tensorflow.Please assign me this take
