### ISSUE TITLE
Diabetes Prediction

### ISSUE THREAD

**Issue by Jagannath8** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#44]
I want to predict if a person is having diabetes or not.
I'll use Logistic Regression algorithm.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by sai-keerthi** [comment]
can you assign me this issue..

**Comment by Niketkumardheeryan** [comment]
@sai-keerthi @Jagannath8  sorry , we already have many simple linear regression and classification projects in this repo ,so choose other issues or create a better one.
