### ISSUE TITLE
Titanic Passenger Survival Prediction

### ISSUE THREAD

**Issue by atarax665** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#49]
I would like to do exploratory data analysis and predict the survival chances of someone if they were on titanic using Gaussian Naive Bayes. I am looking to use the dataset provided [here](https://www.kaggle.com/brendan45774/test-file?select=tested.csv) for this purpose.

**Comment by Niketkumardheeryan** [comment]
@atarax665 sorry , we already have many simple linear regression and classification projects in this repo ,so choose other issues or create a better one.
