### ISSUE TITLE
Create Readme. File For each PR

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#5]

**Comment by unnati914** [comment]
i can work on this

**Comment by Niketkumardheeryan** [comment]
@unnati914 this pinned issue is only for instructions,you can choose other issues, or create your own issues

**Comment by Kavyapushpala** [comment]
Hello Maintainers,

I would like to contribute a new project: **Plant Disease Detection using Deep Learning**.

Project idea:

* Upload plant leaf image
* Detect disease using ML/CNN model
* Show prediction and confidence score
* (Optional) Provide recommendations

Please let me know if this contribution aligns with the repository guidelines. If approved, I will proceed with implementation and create a PR accordingly.

Thank you.
