### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by payaldutta** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#51]
As the project does not contain Contributing file I would like to add it under  LGMSOC '21.
Kindly assign me.
Thank you.

**Comment by jayant766** [comment]
Please assign to me under LGMSOC'21

**Comment by payaldutta** [comment]
@jayant766 Hey! I am already working on this.

**Comment by payaldutta** [comment]
@Niketkumardheeryan As I am seeing there's already a contribution guidelines added. So, do you still want me to continue with this issue?
Thank You.

**Comment by Niketkumardheeryan** [comment]
NO need ,
