### ISSUE TITLE
Fix the Greeting github-action

### ISSUE THREAD

**Issue by atarax665** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#52]
Right now the greeting github-action shows these messages when a new contributor creates his first issue or pull request.
```issue-message: 'Message that will be displayed on users first issue' ```
```pr-message: 'Message that will be displayed on users first pull request'```

It should be formatted to send a better greeting message to the contributors. Something like:
```issue-message: 'Thank you for opening an issue. :partying_face:' ```
```pr-message: 'Thank you for taking out your time and contributing to our project. Our team will now review this and if everything looks good it will be merged soon.'```

**Comment by Niketkumardheeryan** [comment]
@atarax665 add more useful bots for this repo if u can ...
