### ISSUE TITLE
Different types of Scaling For machine learning models.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#54]

**Comment by Megha0606** [comment]
I wantI want to work on this Issue, Please assign me. Thanks

**Comment by suy1968** [comment]
Please assign me, as I am a part of LGMSOC21 and i work on this isssue

**Comment by SwatiPanchal** [comment]
I would like to contribute. Please assign me

**Comment by usgn94** [comment]
@Niketkumardheeryan  I would like to work on this issue. Could you please assign me

**Comment by shivani6320** [comment]
I would like to contribute to this issue. Please assign me.
