### ISSUE TITLE
Techniques to fill null values in data with code.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#56]

**Comment by arushi09207** [comment]
here as well we need to describe the methods and then submit the pynb ? i would be happy to contribute.

**Comment by SwatiPanchal** [comment]
I would like to contribute

**Comment by arushi09207** [comment]
thanks.  @Niketkumardheeryan

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.
