### ISSUE TITLE
Make the more attractive Readme.md file for this repo

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#6]

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by Niketkumardheeryan** [comment]
Sure @aditya28sarin

**Comment by Sumit11081996** [comment]
Hello, @Niketkumardheeryan I would like to work on this issue as LSM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by harshita9621** [comment]
Hii, @Niketkumardheeryan I would like to work on this issue as LSM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Niketkumardheeryan** [comment]
first come first serve ,but if assignee will delay to make a pr , I will assign it you.

**Comment by Komal-99** [comment]
Kindly assign it to me as the current Readme looks so incomplete with no formation most of the fields are empty.I am LGMSOC participant

**Comment by Niketkumardheeryan** [comment]
@aditya28sarin do it fast ..

**Comment by Niketkumardheeryan** [comment]
@aditya28sarin make a pr for this issue ,otherwise, I will assign it  to others.

**Comment by Niketkumardheeryan** [comment]
@Sumit11081996 @Komal-99 @harshita9621 @aditya28sarin    now all of you can make PR  for this  issue, PR will be  merged  on first come first serve basis.
