### ISSUE TITLE
Handwritten equation solver using CNN

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#62]

**Comment by Sumit11081996** [comment]
hi @Niketkumardheeryan  can you please assign me this issue

**Comment by Niketkumardheeryan** [comment]
@Sumit11081996 u can not work on 2 issues at a time..

**Comment by shivani6320** [comment]
I would like to contribute. Please assign me this project.
