### ISSUE TITLE
Covid-19 Death Rate Analysis with Machine Learning

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#65]

**Comment by Megha0606** [comment]
I want to work on this please assign me, I'm a participant of LGM-SOC'21

**Comment by suy1968** [comment]
Please assign me as I am a participant of LGMSOC21

**Comment by shivani6320** [comment]
Hello. Can you assign me this issue. I am LGM-SOC21 participant. I have all the relevant skills regarding this domain & get best outcome

**Comment by harshita9621** [comment]
Can I work on this issue??

**Comment by Shivani-Khare** [comment]
Hello sir, Please assign me this issue. Really want to work for it. I am LGM-SoC21 participant.

**Comment by SuryanshNaugraiya** [comment]
@Niketkumardheeryan sir please assign the issue #65 to me as i have created an amazing end to end project using html, css, javascript. You can check the screenshots of my project.

![Screenshot (245)](https://user-images.githubusercontent.com/53707393/124252383-845eda80-db44-11eb-8dcf-43e6f84ae023.png)
![Screenshot (246)](https://user-images.githubusercontent.com/53707393/124252392-86c13480-db44-11eb-9d22-f26947d40473.png)
![Screenshot (247)](https://user-images.githubusercontent.com/53707393/124252399-87f26180-db44-11eb-8325-9fe8ec0694fe.png)
![Screenshot (248)](https://user-images.githubusercontent.com/53707393/124252401-888af800-db44-11eb-8733-30a497cbaf7e.png)
![Screenshot (249)](https://user-images.githubusercontent.com/53707393/124252403-89bc2500-db44-11eb-83c4-05d6af21d000.png)
![Screenshot (250)](https://user-images.githubusercontent.com/53707393/124252406-8a54bb80-db44-11eb-9252-6de962594826.png)
![Screenshot (251)](https://user-images.githubusercontent.com/53707393/124252409-8aed5200-db44-11eb-8ce9-2224ce61e46b.png)
![Screenshot (252)](https://user-images.githubusercontent.com/53707393/124252410-8b85e880-db44-11eb-866a-3a8e02dc62f8.png)
![Screenshot (253)](https://user-images.githubusercontent.com/53707393/124252413-8c1e7f00-db44-11eb-92c5-c815155dfc16.png)
