### ISSUE TITLE
Language_Translator_using_Python_and_GoogleAPI

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#66]

**Comment by Megha0606** [comment]
I want to work on this please assign me, I'm a participant of LGM-SOC'21

**Comment by queenish001** [comment]
Please assign this issue to me

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Please assign me this. I want to work on this issue sir.

**Comment by Jyoti6828** [comment]
@Niketkumardheeryan I want to work on this issue. Please assign this issue to me.
