### ISSUE TITLE
Make a Recommendation system .

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#7]
You have to make a recommendation system

**Comment by ayushgoyal9991** [comment]
@Niketkumardheeryan  Is there any specific type of recommendation system we have to make or we are free to choose?

**Comment by Niketkumardheeryan** [comment]
You are free to choose.. @ayushgoyal9991

**Comment by ayushgoyal9991** [comment]
I am interested in contributing as an LGM-SOC participant.

**Comment by Niketkumardheeryan** [comment]
@ayushgoyal9991 go for it

**Comment by ayushgoyal9991** [comment]
Hello, I have completed a content-based recommendation system and uploaded the same in the forked repo. Can you please tell me what do I need to do to make changes in the parent repo?

**Comment by Megha0606** [comment]
Please assign me thia issue

**Comment by Megha0606** [comment]
Any update ? Can I work on this issue?
