### ISSUE TITLE
Basics of Python and ML model code with Explanations

### ISSUE THREAD

**Issue by SurajPawar15-smart** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#70]
Hello sir , what I do from open contribution. please accept my request

**Comment by Niketkumardheeryan** [comment]
@SurajPawar15-smart go for it

**Comment by SuryanshNaugraiya** [comment]
@Niketkumardheeryan sir please assign the issue #70 under LGMSOC21 to me. I want to contribute in this

**Comment by Niketkumardheeryan** [comment]
@SuryanshNaugraiya only add Basics of Machine learning ...

**Comment by Niketkumardheeryan** [comment]
& Deep learning too...

**Comment by SuryanshNaugraiya** [comment]
@Niketkumardheeryan should i add all the ipynb files in one folder called Notes, or should i separately upload all the files?

**Comment by Niketkumardheeryan** [comment]
add a folder named Basics of ML and Dl and put ur all files into it..

**Comment by SuryanshNaugraiya** [comment]
ok
