### ISSUE TITLE
Breast Cancer Prediction 

### ISSUE THREAD

**Issue by Jagannath8** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#72]
##Title
Breast Cancer Prediction 

##Objective
The objective is to predict Breast Cancer using Machine Learning alogithm.

##Dataset
https://www.kaggle.com/uciml/breast-cancer-wisconsin-data

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Niketkumardheeryan** [comment]
@Jagannath8 this repo already has many simple classification model ,so choose or create other issues
