### ISSUE TITLE
Different types of Plots In Seaborn, Matplotlib,Pandas  etc,,

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#74]

**Comment by Sakalya100** [comment]
@Niketkumardheeryan I would like to work on this. Kindly assign me this.

**Comment by harshita9621** [comment]
Hi,I would like to work on this. Kindly assign me this.

**Comment by harshita9621** [comment]
hii @Niketkumardheeryan can you please assign me this i have a great content in the visualization part with the proper example. Kindly assign me this.
