### ISSUE TITLE
create  a Python Package.

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#78]

**Comment by Sakalya100** [comment]
@Niketkumardheeryan I would like to work upon this issue. Kindly assign me this

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Sir What exactly are you expecting for this issue. I am a bit confused so can you explain a bit to me

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Sir Why did I get unassigned . Can you please tell?

**Comment by Niketkumardheeryan** [comment]
@Sakalya100  check ur timing or question u asked...

**Comment by Sakalya100** [comment]
Yes @Niketkumardheeryan sir I understood my mistake. Actually in the middle my laptop got crashed so I was not able to work in those 4 days. Its okay sir first I will finish the one issue then focus on other

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Sir kindly assign me this issue. I want to work on this issue

**Comment by Sakalya100** [comment]
@Niketkumardheeryan Sir thank you for assigning me this issue. But I am a bit confused about this issue. So I want to work on the issue #66 first as I already have some material for that issue. So please assign me that first if possible.
