### ISSUE TITLE
Student's Marks Prediction depending on the study hours

### ISSUE THREAD

**Issue by abhisheks008** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#83]
Hello admin, In this project I an going to predict the marks of a particular student based on the fact the how many study hours that student is having.

Tool used : Jupyter Notebook
Dataset : [student study hours](http://bit.ly/w-data)
Method : Supervised Learning
Algorithm used : Linear Regression

This project will be a great example of Supervised Machine Learning. @Niketkumardheeryan Please assign me this task.

**Comment by Niketkumardheeryan** [comment]
@abhisheks008 sorry no more simple linear regression allowed ,bcz it is already there... choose or create other issues.
