### ISSUE TITLE
Create a file of SQL Commands

### ISSUE THREAD

**Issue by Niketkumardheeryan** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#86]

**Comment by abhisheks008** [comment]
Can I work in it after completing my issue?

**Comment by Niketkumardheeryan** [comment]
@abhisheks008 complete that issue first

**Comment by abhisheks008** [comment]
I have fixed the issue #85 by successfully merging the PR #89. Can I now work on this issue?
@Niketkumardheeryan Please assign this to me.
Thank you!

**Comment by abhisheks008** [comment]
Do I have to create a SQL file or, I can explain the commands using a markdown file. Which one will be preferable? @Niketkumardheeryan

**Comment by abhisheks008** [comment]
Can you please share the format, it will be easier for me to work on
