### ISSUE TITLE
Water Quality Prediction

### ISSUE THREAD

**Issue by Jagannath8** [Niketkumardheeryan/Hands-on-ML-Basic-to-Advance-#99]
Title: Water Quality Prediction
Objective: The main objective of this project is to predicting the water quality based on the dataset provided using machine learning algorithms.
Dataset: https://www.kaggle.com/adityakadiwal/water-potability
About: Create model

Approach: I will use multiple machine learning algorithms to compare the accuracy.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Niketkumardheeryan** [comment]
@Jagannath8 sorry no more simple ml model, bcz many simple models are there.. choose or create  other issue
